### ISSUE TITLE
公用API失效了

### ISSUE THREAD

**Issue by Uzizkp** [Zfour/python_github_calendar_api#3]
githubcalendar.js:58 
        GET https://python-github-calendar-api.vercel.app/api?USER net::ERR_CONNECTION_CLOSED
github_canlendar @ githubcalendar.js:58
(匿名) @ githubcalendar.js:312
(匿名) @ githubcalendar.js:313
githubcalendar.js:81 TypeError: Failed to fetch
    at github_canlendar (githubcalendar.js:58:5)
    at githubcalendar.js:312:5
    at githubcalendar.js:313:3

**Comment by Zfour** [comment]
https://gitcalendar.zfe.space/api

**Comment by Zfour** [comment]
建议自建api，绑定域名。替换公共域名。

**Comment by Zfour** [comment]
![image](https://user-images.githubusercontent.com/19563906/188314731-bb849961-9aed-43a9-8315-97de1ee5f05c.png)

**Comment by Zfour** [comment]
vercel.app域名被墙，使用需自定义域名绑定

**Comment by kp-z** [comment]
> vercel.app域名被墙，使用需自定义域名绑定

感谢，用了https://gitcalendar.zfe.space/api这个可以了
